#!/usr/bin/env bash
# This script does a bunch of things which at the moment of writing this, i do not feel like explaining.

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'rm -f /var/run/myscript.pid' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true
do
echo "To infinity and beyond"
done
