#!/usr/bin/env bash
# This script does a bunch of things which at the moment of writing this, i do not feel like explaining.

PID=$$
echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'rm /var/run/myscript.pid' SIGTERM SIGQUIT
trap 'kill $PID' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

while true
do
echo "To infinity and beyond"
done
