#!/usr/bin/env bash
# This script manages the process of the file 'manage_my_process'

start() {
    # code to start app comes here 
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
}

stop() {
    # code to stop app comes here 
    kill -9 "$( cat /var/run/my_process.pid )"
    rm -f /var/run/my_process.pid
}

case "$1" in 
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0 
